# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'

Options:
 cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
 cppcheck-arguments: '--enable=warning,performance,portability,style --suppress-xml=cppcheck-suppressions.xml -DQTEST_AKONADIMAIN\(X\)= -DQTEST_AKONADI_CORE_MAIN\(X\)= -D__GLIBC_PREREQ\(X,Y\)=1 -DPOSTGRES_PATH=\"/path/to/pg_ctl\" -DMYSQLD_EXECUTABLE=\"/path/to/mysqld\"'
 cppcheck-ignore-files:
   - templates
   - autotests/libs/searchquerytest.cpp
 run-gcovr: "--gcov-ignore-parse-errors=negative_hits.warn"
 run-qmllint: true
