# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'

Options:
 cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
 cppcheck-arguments:
   - --enable=warning,performance,portability,style
   - --suppress-xml=cppcheck-suppressions.xml
   - -DQTEST_AKONADIMAIN(X)=
   - -DQTEST_AKONADI_CORE_MAIN(X)=
   - -D__GLIBC_PREREQ(X,Y)=1
   - -DPOSTGRES_PATH="/path/to/pg_ctl"
   - -DMYSQLD_EXECUTABLE="/path/to/mysqld"
   - -DMYSQLD_SCRIPTS_PATH="/path/to/mysqld"
 cppcheck-ignore-files:
   - templates
   - autotests/libs/searchquerytest.cpp
 run-gcovr: "--gcov-ignore-parse-errors=negative_hits.warn"
 run-qmllint: true
