# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kdesignerplugin' : '@latest'
    'kde/kdenetwork/kaccounts-integration' : '@latest'
