#cmakedefine HAVE_EXECINFO_H 1
#cmakedefine HAVE_UNISTD_H 1

#define AKONADI_MAJOR_VERSION @AKONADI_LIB_MAJOR_VERSION@
#define AKONADI_MINOR_VERSION @AKONADI_LIB_MINOR_VERSION@
#define AKONADI_PATCH_VERSION @AKONADI_LIB_PATCH_VERSION@
#define AKONADI_VERSION_STRING "@AKONADI_LIB_VERSION_STRING@"
