#cmakedefine01 Backtrace_FOUND
#if Backtrace_FOUND
# include <@Backtrace_HEADER@>
#endif

#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_SOPRANO 1

#define AKONADI_VERSION_MAJOR @AKONADI_VERSION_MAJOR@
#define AKONADI_VERSION_MINOR @AKONADI_VERSION_MINOR@
#define AKONADI_VERSION_PATCH @AKONADI_VERSION_PATCH@
#define AKONADI_VERSION_STRING "@AKONADI_VERSION_STRING@"

#define AKONADI_DATABASE_BACKEND "@AKONADI_DATABASE_BACKEND@"
