# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += src qtest
TEMPLATE = subdirs

test.target=test
test.commands= cd qtest && make test
test.depends = all $(TARGET)
QMAKE_EXTRA_TARGETS += test

