######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 23 18:45:44 2012
######################################################################

TEMPLATE = app
TARGET = etmcalendar
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
INCLUDEPATH += /usr/include/KDE

LIBS += -lakonadi-calendar -lkdecore
